### PR TITLE
Remove height requirement

### PR DESCRIPTION
**Pull request by Jeradin**
Remove the height being required as the options variable for height is optional.

### CODE REVIEW

**Comment by timsamuelsson** [comment]
Please can you accept this pull request, or update the documentation.

Thanks in advance!

**Comment by rubenbristian** [comment]
Please approve this commit - the height is not optional, if you upload an image without a height it will not work..

**Comment by mikaelengstrom** [comment]
@Jeradin Could you please look in to this?

**Comment by mikaelengstrom** [comment]
@syamilmj Could you please look in to this?

**Comment by timsamuelsson** [comment]
You can set height = -1, it should work if you want an unspecified height!

**Pull request merged**
